apiVersion: v1
kind: Service
metadata:
  name: python-test-app-svc
  namespace: prod  
spec:
  type: ClusterIP
  selector:
    app: python-test-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
